export const centurionLegionModes = [
  {
    id: 'mini',
    title: 'Mini-Battle',
    desc: 'easy, short challenges\nbetween 2 players',
    icon: require('../../assets/images/centurionbattle1.png'),
  },
  {
    id: 'courage',
    title: 'Courage',
    desc: 'easy, fun actions',
    icon: require('../../assets/images/centurionbattle2.png'),
  },
  {
    id: 'memory',
    title: 'Memory and logic',
    desc: 'simple',
    icon: require('../../assets/images/centurionbattle3.png'),
  },
  {
    id: 'dynamic',
    title: 'Dynamic',
    desc: 'something a little more\nactive',
    icon: require('../../assets/images/centurionbattle4.png'),
  },
];

export const centurionLegionTasksMini = [
  'Who will touch the floor faster.',
  'Who will say “GLORIA!” louder.',
  'Who will raise their hand up faster.',
  'Who will find any red thing faster.',
  'Who will make the funniest face.',
  'Who will not blink longer.',
  'Who will be the first to name an animal.',
  'Who will tap the table three times faster.',
  'Who will come up with a Roman name faster.',
  'Who will stomp their foot louder.',
  'Who will sit down and stand up first.',
  'Who will make the best gladiator pose.',
  'Who will touch the wall faster.',
  'Who will hold a wide smile longer.',
  'Who will name any fruit faster.',
  'Who will shout Roman “HURRAY!” louder.',
  'Who will pick up a small item faster.',
  'Who will depict a strong hero better.',
  'Who will name a city faster.',
];
export const centurionLegionTasksCourage = [
  'Make a victory pose for 3 seconds.',
  'Compliment the player on your left.',
  'Impersonate a Roman hero.',
  'Make any funny sound.',
  'Come up with a Roman name.',
  'Say “Glory to the Legion!”.',
  'Show your most serious facial expression.',
  'Create a Roman rule of honor.',
  'Walk like a proud legionnaire.',
  'Say a phrase with pathos.',
  'Impersonate someone from the company.',
  'Show centurion gesture.',
  'Say 3 solemn words.',
  'Show how you hold a shield.',
  'Make a “battle” cry.',
  'Create a legion motto.',
  'Show an “I won” face.',
  'Draw a circle in the air.',
  'Show your happy face.',
  'Come up with a character nickname.',
];
export const centurionLegionTasksMemory = [
  'Name three cities.',
  'Name three objects around you.',
  'Say a word without “A”.',
  'Name a fruit in 3 seconds.',
  'Name two countries.',
  'Name three animals.',
  'Say any color.',
  'Name two vegetables.',
  'Repeat the word of the player on the right.',
  'Name three things you love.',
  'Name any historical era.',
  'Say a word starting with P.',
  'Name three actions in 3 seconds.',
  'Name any hobby.',
  'Name a day of the week.',
  'Say any food.',
  'Name three letters in order.',
  'Name two emotions.',
  'Name a profession.',
  'Say a word longer than 5 letters.',
];
export const centurionLegionTasksDynamic = [
  'Run in place for 3 seconds.',
  'Clap your hands three times.',
  'Turn around once.',
  'Do a charioteer step.',
  'Wave your hand like a flag.',
  'Touch the floor.',
  'Jump once.',
  'Move hands back/forth.',
  'Show a shield blow.',
  'Raise hands for 2 seconds.',
  'Step feet twice rhythmically.',
  'Make “Forward, legion!” gesture.',
  'Bend right/left.',
  'Turn head left/right.',
  'Pick any object nearby.',
  'Squat once.',
  'Take 2 steps forward/back.',
  'Hit fist on palm like in movies.',
  'Raise one shoulder then the other.',
  'Make a short fighting motion.',
];
